install python dependencies by pip
ipa320/araig_test_stack pull request #11
Opened 2021-01-14 19:52 UTC by ipa-rwu

pip install -m requirement.txt
if rosdep resolve <pkg> return error

2021-01-15 07:39 UTC, ipa-kut commented on README.md
> +# araig_test_stack
Please Insert:

# ARAIG Test Stack
This stack contains the GUI, calculators, interpreters and runners required to implement any ARAIG test. 

The actual launch files per robot will be stored in [araig_robot_packages](https://github.com/ipa320/araig_robot_packages)

Benchmarking for these components per test will be stored in [araig_benchmarks](https://github.com/ipa320/araig_benchmarks)

## Requirements

Install python dependencies not supported by rosdep with:
`pip install -m requirement.txt`

2021-01-15 07:39 UTC, ipa-kut commented on requirement.txt
> +asyncio ; python_version == '3.6'
Please add scipy as well

2021-01-15 07:40 UTC, ipa-kut requested changes
Please update the readme and add scipy

2021-01-15 09:43 UTC, ipa-rwu commented
rosdep support scipy
you can check by 
`rosdep resolve python-scipy`

2021-01-15 12:37 UTC, ipa-kut commented
> rosdep support scipy
> you can check by
> `rosdep resolve python-scipy`

Yes but `rosdep install python-scipy` does not work for me. Does it work for you?

2021-01-18 13:50 UTC, ipa-kut approved these changes

2021-01-18 13:51 UTC, merged