Rwu/enh/runner
ipa320/araig_test_stack pull request #22
Opened 2021-02-10 08:46 UTC by ipa-rwu

2021-02-10 08:49 UTC, ipa-rwu commented on araig_test_runners/scripts/test_4_static_obstacle
> +            self.current_state = State.complete_test
#20 
runner will keep checking if it gets *signal.calc.robot_reached_goal_and_stopped*

2021-03-16 13:17 UTC, ipa-kut requested changes
Seems like test 5 still needs to be refactored to the newer state-machine bound resetable format.

2021-03-16 13:17 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +            "timeout_check_goal",
can be renamed to `timeout_check_goal_oscillations`

2021-03-16 13:17 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +                if self.checkCondition(self.getSafeFlag("goal", header = True).stamp, \
I dont completely understand what is being checked here...

2021-03-16 13:17 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +        if self.current_state == State.start_test and self.getSafeFlag("goal"):
okay checking for oscillations. I get why you do this, but as before, the test itself should not try to compensate for oscillations. So the goal time checking is done immediately as the robot reaches goal, as that is the specification of this test. Checking for oscillations is an addendum, and if you remember our old discussion, we can just count the number of times the robot has oscillated and show that in the UI/log it.

In general, tests should not be altered to accommodate for shortcomings in the test subjects.

2021-03-16 13:17 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +        # Test complete if robot doesn't move any more and reached the goal
Well if the oscillations are undamped, this is basically an infinite loop :P So lets not try to compensate for it.

2021-03-16 13:17 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +        # If test complete, wait for "timeout_after_complete" s, then enable reset
What is the need for timeout after complete? I originally thought this was oscillation compensation, but seems to not be the case?

2021-03-16 15:21 UTC, ipa-kut commented on araig_test_runners/scripts/test_1_braking
> +            self.startRecordingAndWait(3)
Wait so how do you actually trigger start of rosbagger? :thinking:

2021-03-16 15:29 UTC, ipa-kut commented on araig_test_runners/src/base/base_runner.py
> -        self._publishers["start_recording"].publish(self.buildNewBoolStamped(True))
If this is removed, who tells the bagger to start recording?

2021-03-19 15:52 UTC, ipa-kut commented on araig_test_runners/scripts/test_1_braking
> +            self.startRecordingAndWait(3)
TODO: Create a proper way to handle sequence of runner signals, folder creatin, loggers starting - stopping, folder renaming etc...

2021-03-19 16:31 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +        if self.current_state == State.start_test and self.getSafeFlag("goal"):
Checking for oscillations is good. So if does oscillate, then count the number, and report a third result category: test_oscillated.   
 
Verify/implement a timeout to number of oscillations that the runner can check. If more, then fail.   

Finally, log the number of oscillations. (Figure out how)

2021-03-19 16:33 UTC, ipa-kut commented on araig_test_runners/scripts/test_4_static_obstacle
> +        # If test complete, wait for "timeout_after_complete" s, then enable reset
RWU: To protect the folder logger from being interrupted as it changes the folder name.

2021-04-19 15:58 UTC, ipa-kut commented
This PR is superseded by https://github.com/ipa320/araig_test_stack/pull/35 and no longer required. Branch can be kept as archive.

2021-04-19 15:58 UTC, closed without merging