add test3 runner
ipa320/araig_test_stack pull request #63
Opened 2021-06-01 06:30 UTC by ipa-rwu

We can publish "/signal/user/check/succeed" True or "/signal/user/check/failed" True

2021-06-08 08:11 UTC, ipa-kut commented
> We can publish "/signal/ui/check/succeed" True or "/signal/ui/check/failed" True

What do you imagine the success and failure conditions are,  given that this is a purely qualitative test?

2021-06-08 08:25 UTC, ipa-kut requested changes
I see that you designed this test to be purely observational only without any intervention. However, we should stay conformant with the principle of the other tests in that we control the robot - We should start/stop the robot via our GUI and automatically infer the results thereafter. This will ensure that we always provide a precisely constant velocity to the robot for a precisely set  amount of time. Doing this with teleop will be inconsistent.

Consequently, the definition of success/failure would also change - if the robot starts up and stops only when we command it to, it is a success. If it stops before we tell it to, we could consider it a failure.

2021-06-14 09:10 UTC, ipa-rwu commented
I don't think we need/can provide velocity by us. Test3 is for a qualitative test, not a quantitative test. E.g. we want to test the robot go through ramp, we want to see if it can succeed.

But I think it will be nice to add another test runner where we provide speed.

For success and failure, if a robot can not go through the ramp, it fails. 
And if you follow the principle of the other tests, it always has success and failure. E.g. robot goes through different surfaces, if it slips, the test fails.

2021-07-27 11:53 UTC, ipa-kut approved these changes

2021-07-27 11:53 UTC, merged